version: '3.3'

services:

  tin-terrain:
      restart: "no"
      container_name: "tin-terrain"
      image: "tin-terrain:latest"
      volumes:
          - "./:/data:cached"
      working_dir: "/data"
      entrypoint: "/data/entrypoint.sh"

